# Generated by Django 3.2.24 on 2024-02-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resultado',
            new_name='Reaccion',
        ),
    ]
