# Generated by Django 3.2.24 on 2024-02-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_auto_20240215_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.categoria'),
        ),
    ]
