# Generated by Django 3.2.24 on 2024-02-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_categoria_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
