# Generated by Django 3.2.24 on 2024-02-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_alter_categoria_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='normalized',
            field=models.CharField(default='hogar', max_length=50),
            preserve_default=False,
        ),
    ]
