# Generated by Django 3.2.24 on 2024-02-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icon',
        ),
    ]
