# Generated by Django 3.2.24 on 2024-02-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_categoria_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('hex_color', models.CharField(default='000000', max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='icono',
            old_name='className',
            new_name='class_name',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='color',
        ),
    ]
