# Generated by Django 3.2.24 on 2024-03-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0014_categoria_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='sensation',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
