# Generated by Django 3.2.24 on 2024-03-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0015_alter_tarea_sensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='sensation',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
